<div class="media media[field:global name=autoindex runphp="yes"]@me=@me;[/field:global]">
            <div class="media-left media-middle"> <a href="[field:arcurl/]"> [field:global name=autoindex runphp="yes"]@me=@me;[/field:global] </a> </div>
            <div class="media-body"> <a href="[field:arcurl/]" class="media-heading">[field:title/]</a>
              <p>　　[field:description function='cn_substr(@me,250)'/]...</p>
            </div>
          </div>