<?php
$z[0]=Array("field","",202,221);
$z[0][4]['name']="title";
$z[1]=Array("global","",222,248);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",289,318);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",358,416);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",742,777);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\r\n    <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n    ",887,1071);
$z[5][4]['type']="son";
$z[5][4]['currentstyle']="<li><a href='~typelink~' class='hover'>~typename~</a></li>";
$z[6]=Array("list","\r\n    <div class=\"col-md-3 col-sm-4 col-xs-6\"> <a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" class=\"img-responsive\"></a> <a href=\"[field:arcurl/]\"><span>[field:title/]</span></a> </div>\r\n    ",1189,1438);
$z[6][4]['pagesize']="12";
$z[6][4]['titlelen']="50";
$z[7]=Array("pagelist","",1524,1590);
$z[7][4]['listitem']="index,end,pre,next,pageno";
$z[7][4]['listsize']="3";
$z[8]=Array("include","",1625,1660);
$z[8][4]['filename']="foot.htm";

?>